"""add sensing_counts table

Revision ID: 1701d0a1046e
Revises: 881d2c4c844c
Create Date: 2024-11-16 16:53:50.293551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1701d0a1046e'
down_revision = '881d2c4c844c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensing_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('optionA_count', sa.Integer(), nullable=False),
    sa.Column('optionB_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensing_counts')
    # ### end Alembic commands ###
