"""Add Questions table.

Revision ID: 419315083c2a
Revises: ff4ba99f56fe
Create Date: 2024-11-07 11:05:33.655194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419315083c2a'
down_revision = 'ff4ba99f56fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.String(length=255), nullable=True),
    sa.Column('optionA', sa.String(length=255), nullable=True),
    sa.Column('optionB', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
